# Generated by Django 6.0.2 on 2026-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
